#  Name of workflow
name: CI/CD

on:
  push:
    tags:
      - 'v*'

# Jobs to carry out
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our production secrets
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
